[workspace]
resolver = "2"
members = [
  "quickwit-actors",
  "quickwit-aws",
  "quickwit-cli",
  "quickwit-cluster",
  "quickwit-codegen",
  "quickwit-codegen/example",
  "quickwit-common",
  "quickwit-config",
  "quickwit-control-plane",
  "quickwit-index-management",
  "quickwit-datetime",
  "quickwit-directories",
  "quickwit-doc-mapper",
  "quickwit-indexing",
  "quickwit-ingest",
  "quickwit-integration-tests",
  "quickwit-jaeger",
  "quickwit-janitor",
  "quickwit-macros",
  "quickwit-macros/impl",
  "quickwit-metastore",
  # Disabling metastore-utils from the quicwit projects to ease build/deps.
  # We can reenable it when we need it.
  # "quickwit-metastore-utils",
  "quickwit-opentelemetry",
  "quickwit-proto",
  "quickwit-query",
  "quickwit-rest-client",
  "quickwit-search",
  "quickwit-serve",
  "quickwit-storage",
  "quickwit-telemetry",
]

[profile.dev]
debug = false

[workspace.dependencies]
anyhow = "1"
arc-swap = "1.6"
assert-json-diff = "2"
async-speed-limit = "0.4"
async-trait = "0.1"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.21"
brotli = "3.3.0"
bytes = { version = "1", features = ["serde"] }
bytesize = { version = "1.3.0", features = ["serde"] }
bytestring = "1.3.0"
chitchat = { git = "https://github.com/quickwit-oss/chitchat.git", rev = "a3e3f8b" }
chrono = { version = "0.4.23", default-features = false, features = [
  "clock",
  "std",
] }
clap = { version = "4.4.1", features = ["env", "string"] }
colored = "2.1.0"
console-subscriber = "0.1.8"
criterion = { version = "0.5", features = ["async_tokio"] }
cron = "0.12.0"
dialoguer = "0.10.3"
dotenv = "0.15"
dyn-clone = "1.0.10"
enum-iterator = "1.5"
env_logger = "0.10"
fail = "0.5"
flate2 = "1.0.20"
flume = "0.11"
fnv = "1"
futures = "0.3"
futures-util = { version = "0.3.25", default-features = false }
google-cloud-auth = "0.12.0"
google-cloud-default = { version = "0.3.0", features = ["pubsub"] }
google-cloud-gax = "0.15.0"
google-cloud-googleapis = { version = "0.10.0", features = ["pubsub"] }
google-cloud-pubsub = "0.18.0"
heck = "0.4.1"
hex = "0.4.3"
home = "0.5.4"
hostname = "0.3"
http = "0.2.9"
http-serde = "1.1.2"
humansize = "2.1.3"
humantime = "2.1.0"
hyper = { version = "0.14", features = [
  "client",
  "http1",
  "http2",
  "server",
  "stream",
  "tcp",
] }
hyper-rustls = "0.24"
indexmap = { version = "2.1.0", features = ["serde"] }
indicatif = "0.17.3"
itertools = "0.12"
json_comments = "0.2"
libz-sys = "1.1.8"
lru = "0.12"
lindera-core = "0.27.0"
lindera-dictionary = "0.27.0"
lindera-tokenizer = { version = "0.27.0", features = [
  "cc-cedict-compress",
  "cc-cedict",
  "ipadic-compress",
  "ipadic",
  "ko-dic-compress",
  "ko-dic",
] }
matches = "0.1.9"
md5 = "0.7"
mime_guess = "2.0.4"
mockall = "0.11"
mrecordlog = { git = "https://github.com/quickwit-oss/mrecordlog", rev = "2914cad" }
new_string_template = "1.4.0"
nom = "7.1.3"
num_cpus = "1"
numfmt = "1.1.1"
once_cell = "1"
oneshot = "0.1.5"
openssl = { version = "0.10.60", default-features = false }
openssl-probe = "0.1.5"
opentelemetry = { version = "0.20", features = ["rt-tokio"] }
opentelemetry-otlp = "0.13.0"
ouroboros = "0.18.0"
percent-encoding = "2.3.1"
pin-project = "1.1.0"
pnet = { version = "0.33.0", features = ["std"] }
postcard = { version = "1.0.4", features = [
  "use-std",
], default-features = false }
predicates = "3"
prettyplease = "0.2.0"
proc-macro2 = "1.0.50"
prometheus = { version = "0.13", features = ["process"] }
proptest = "1"
prost = { version = "0.11.6", default-features = false, features = [
  "prost-derive",
] }
prost-build = "0.11.6"
prost-types = "0.11.6"
pulsar = { git = "https://github.com/quickwit-oss/pulsar-rs.git", rev = "f9eff04", default-features = false, features = [
  "auth-oauth2",
  "compression",
  "tokio-runtime",
] }
quote = "1.0.23"
rand = "0.8"
rand_distr = "0.4"
rayon = "1"
rdkafka = { version = "0.33", default-features = false, features = [
  "cmake-build",
  "libz",
  "ssl",
  "tokio",
  "zstd",
] }
regex = "1.10.0"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
rust-embed = "6.8.1"
sea-query = { version = "0" }
sea-query-binder = { version = "0", features = [
  "runtime-tokio-rustls",
  "sqlx-postgres",
] }
# ^1.0.184 due to serde-rs/serde#2538
serde = { version = "1.0.184", features = ["derive", "rc"] }
serde_json = "1.0"
serde_qs = { version = "0.12", features = ["warp"] }
serde_with = "3.4.0"
serde_yaml = "0.9"
siphasher = "0.3"
sqlx = { version = "0.7", features = [
  "migrate",
  "postgres",
  "runtime-tokio-rustls",
  "time",
] }
syn = { version = "2.0.11", features = ["extra-traits", "full", "parsing"] }
sync_wrapper = "0.1.2"
tabled = { version = "0.14", features = ["color"] }
tempfile = "3"
termcolor = "1"
thiserror = "1"
thousands = "0.2.0"
tikv-jemalloc-ctl = "0.5"
tikv-jemallocator = "0.5"
time = { version = "0.3.17", features = ["std", "formatting", "macros"] }
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["full"] }
toml = "0.7.6"
tonic = { version = "0.9.0", features = ["gzip"] }
tonic-build = "0.9.0"
tower = { version = "0.4.13", features = [
  "balance",
  "buffer",
  "load",
  "retry",
  "util",
] }
tower-http = { version = "0.4.0", features = ["compression-gzip", "cors"] }
tracing = "0.1.37"
tracing-opentelemetry = "0.20.0"
tracing-subscriber = { version = "0.3.16", features = [
  "env-filter",
  "std",
  "time",
] }
ttl_cache = "0.5"
typetag = "0.2"
ulid = "1.1"
username = "0.2"
utoipa = "3.5.0"
uuid = { version = "1.6", features = ["v4", "serde"] }
vrl = { version = "0.8.1", default-features = false, features = [
  "compiler",
  "diagnostic",
  "stdlib",
  "value",
] }
warp = "0.3"
whichlang = { git = "https://github.com/quickwit-oss/whichlang", rev = "fe406416" }
wiremock = "0.5"
zstd = "0.13.0"

aws-config = "0.55.0"
aws-credential-types = { version = "0.55.0", features = [
  "hardcoded-credentials",
] }
aws-sdk-kinesis = "0.28.0"
aws-sdk-s3 = "0.28.0"
aws-smithy-async = "0.55.0"
aws-smithy-client = "0.55.0"
aws-smithy-http = "0.55.0"
aws-smithy-types = "0.55.0"
aws-types = "0.55.0"

azure_core = { version = "0.13.0", features = ["enable_reqwest_rustls"] }
azure_storage = { version = "0.13.0", default-features = false, features = [
  "enable_reqwest_rustls",
] }
azure_storage_blobs = { version = "0.13.0", default-features = false, features = [
  "enable_reqwest_rustls",
] }

opendal = { version = "0.44", default-features = false }
reqsign = { version = "0.14", default-features = false }

quickwit-actors = { version = "0.7.0", path = "./quickwit-actors" }
quickwit-aws = { version = "0.7.0", path = "./quickwit-aws" }
quickwit-cluster = { version = "0.7.0", path = "./quickwit-cluster" }
quickwit-codegen = { version = "0.7.0", path = "./quickwit-codegen" }
quickwit-codegen-example = { version = "0.7.0", path = "./quickwit-codegen/example" }
quickwit-common = { version = "0.7.0", path = "./quickwit-common" }
quickwit-config = { version = "0.7.0", path = "./quickwit-config" }
quickwit-control-plane = { version = "0.7.0", path = "./quickwit-control-plane" }
quickwit-index-management = { version = "0.7.0", path = "./quickwit-index-management" }
quickwit-datetime = { version = "0.7.0", path = "./quickwit-datetime" }
quickwit-directories = { version = "0.7.0", path = "./quickwit-directories" }
quickwit-doc-mapper = { version = "0.7.0", path = "./quickwit-doc-mapper" }
quickwit-indexing = { version = "0.7.0", path = "./quickwit-indexing" }
quickwit-ingest = { version = "0.7.0", path = "./quickwit-ingest" }
quickwit-integration-tests = { version = "0.7.0", path = "./quickwit-integration-tests" }
quickwit-jaeger = { version = "0.7.0", path = "./quickwit-jaeger" }
quickwit-janitor = { version = "0.7.0", path = "./quickwit-janitor" }
quickwit-macros = { version = "0.7.0", path = "./quickwit-macros" }
quickwit-macros-impl = { version = "0.7.0", path = "./quickwit-macros/impl" }
quickwit-metastore = { version = "0.7.0", path = "./quickwit-metastore" }
quickwit-opentelemetry = { version = "0.7.0", path = "./quickwit-opentelemetry" }
quickwit-proto = { version = "0.7.0", path = "./quickwit-proto" }
quickwit-query = { version = "0.7.0", path = "./quickwit-query" }
quickwit-rest-client = { version = "0.7.0", path = "./quickwit-rest-client" }
quickwit-search = { version = "0.7.0", path = "./quickwit-search" }
quickwit-serve = { version = "0.7.0", path = "./quickwit-serve" }
quickwit-storage = { version = "0.7.0", path = "./quickwit-storage" }
quickwit-telemetry = { version = "0.7.0", path = "./quickwit-telemetry" }

tantivy = { git = "https://github.com/quickwit-oss/tantivy/", rev = "014328e", default-features = false, features = [
  "lz4-compression",
  "mmap",
  "quickwit",
  "zstd-compression",
] }

# This is actually not used directly the goal is to fix the version
# used by reqwest.
encoding_rs = "=0.8.32"

[patch.crates-io]
sasl2-sys = { git = "https://github.com/quickwit-oss/rust-sasl/", rev = "daca921" }

## this patched version of tracing helps better understand what happens inside futures (when are
## they polled, how long does poll take...)
#tracing = { git = "https://github.com/trinity-1686a/tracing.git", rev = "6806cac3" }
#tracing-attributes = { git = "https://github.com/trinity-1686a/tracing.git", rev = "6806cac3" }
#tracing-core = { git = "https://github.com/trinity-1686a/tracing.git", rev = "6806cac3" }
#tracing-futures = { git = "https://github.com/trinity-1686a/tracing.git", rev = "6806cac3" }
#tracing-log = { git = "https://github.com/trinity-1686a/tracing.git", rev = "6806cac3" }
#tracing-opentelemetry = { git = "https://github.com/trinity-1686a/tracing.git", rev = "6806cac3" }
#tracing-subscriber = { git = "https://github.com/trinity-1686a/tracing.git", rev = "6806cac3" }
